### ISSUE TITLE
vike-server and hono node-server serve

### ISSUE THREAD

**Issue by fortezhuo** [vikejs/vike-server#86]
In @hono/node-server server method. we can add callback method and implement https (for dev purpose),
I don't get how implement https and callback for register cronjob using vike-server's serve ?

```ts
import { Scheduler } from "@/server/lib/scheduler"
import { serve } from "@hono/node-server"
import { Hono } from "hono"
import { loadHttps, printConsole, activateCronJob, port } from "./util"
import { apply } from "vike-server/hono"

import { dirname } from "node:path"
import { resolve } from "node:path"
import { fileURLToPath } from "node:url"

const __filename = fileURLToPath(import.meta.url)
const root = dirname(__filename)
export const distClient = resolve(root, "../client")

const ssr = {
  pageContext: (unknown: any) => {
    const c = !!unknown["hono"] ? unknown["hono"] : unknown
    return {
      preference: c.var.preference,
      user: c.var.user,
      vendor: c.var.vendor,
    }
  },
  static: {
    root: distClient,
  },
}

const instance = new Hono() 
// add some plugin
apply(instance,ssr)

export function boot(instance: Hono) {
  const https = loadHttps()
  return serve(
    {
      fetch: instance.fetch,
      overrideGlobalObjects: false,
      port,
      ...https,
    },
    () => {
      printConsole()
     activateCronJob()
    },
  )
}
boot(instance)
```

**Comment by nitedani** [comment]
@magne4000 We can forward most(if not all) @hono/node-server options to https://github.com/vikejs/vike-server/blob/main/packages/vike-server/src/handlers/adapters/serve/node/hono.ts#L7, right?

Same question for all others(express, etc...).
I think the main advantage of `vike-server` approach compared to how others do it, is that we can do this.

**Comment by magne4000** [comment]
> [@magne4000](https://github.com/magne4000) We can forward most(if not all) @hono/node-server options to https://github.com/vikejs/vike-server/blob/main/packages/vike-server/src/handlers/adapters/serve/node/hono.ts#L7, right?
> 
> Same question for all others(express, etc...). I think the main advantage of `vike-server` approach compared to how others do it, is that we can do this.

Yes we should do that.
Not sure how everything works with HTTPS though, we should test this thoroughly.

**Comment by magne4000** [comment]
PR in progress: https://github.com/vikejs/vike-server/pull/88

**Comment by magne4000** [comment]
Fixed in `1.0.3`

**Comment by magne4000** [comment]
> I got this error
> 
> ```
> Error: You stumbled upon a bug in vike-server's source code. Reach out on GitHub and we will fix the bug.
>     at assert (file:///Users/forte/Workspace/HCML/ivone/node_modules/.pnpm/vike-server@1.0.4_hono@4.7.5_vike@0.4.227-commit-68a216b_react-streaming@0.4.2_react-do_e25fd92738c95fd4ef7ead7199e48a56/node_modules/vike-server/dist/chunk-2NAYC6FW.js:4:9)
>     at initializeServerEntry (file:///Users/forte/Workspace/HCML/ivone/node_modules/.pnpm/vike-server@1.0.4_hono@4.7.5_vike@0.4.227-commit-68a216b_react-streaming@0.4.2_react-do_e25fd92738c95fd4ef7ead7199e48a56/node_modules/vike-server/dist/config.js:201:5)
> [vite] Server crash: Update a server file or type "r+enter" to restart the server.
>   ➜  press h + enter to show help
> ```

Could you provide a minimal reproduction?

**Comment by nitedani** [comment]
https://github.com/vikejs/vike-server/blob/3b4ddf191f98c66037f661b0f4e68cc5b2e97fa9/packages/vike-server/src/plugin/plugins/devServerPlugin.ts#L197

The server entry path is not resolved relative to the +config.ts file, it can be unintuitive and cause this error.
The server entry path is resolved from the project root folder.

**Comment by fortezhuo** [comment]
@nitedani 
After editing the server entry path, I can run the dev server, but building still results in an error.

Here the repo : https://github.com/fortezhuo/vike-server

```
✓ 0 modules transformed.
✗ Build failed in 3ms
Error during build:
[commonjs--resolver] [plugin commonjs--resolver] There was an error during the build:
  [vike@0.4.227-commit-68a216b][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new?template=bug.yml and copy-paste this error. A maintainer will fix the bug (usually within 24 hours).
Additionally, handling the error in the 'buildEnd' hook caused the following error:
  You stumbled upon a bug in vike-server's source code. Reach out on GitHub and we will fix the bug.
    at getRollupError (file:///Users/forte/Downloads/vike-server/node_modules/.pnpm/rollup@4.37.0/node_modules/rollup/dist/es/shared/parseAst.js:397:41)
    at file:///Users/forte/Downloads/vike-server/node_modules/.pnpm/rollup@4.37.0/node_modules/rollup/dist/es/shared/node-entry.js:22876:39
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at catchUnfinishedHookActions (file:///Users/forte/Downloads/vike-server/node_modules/.pnpm/rollup@4.37.0/node_modules/rollup/dist/es/shared/node-entry.js:22330:16)
    at rollupInternal (file:///Users/forte/Downloads/vike-server/node_modules/.pnpm/rollup@4.37.0/node_modules/rollup/dist/es/shared/node-entry.js:22859:5)
    at buildEnvironment (file:///Users/forte/Downloads/vike-server/node_modules/.pnpm/vite@6.2.3_@types+node@22.13.13_jiti@2.4.2_lightningcss@1.29.2_tsx@4.19.3/node_modules/vite/dist/node/chunks/dep-DDxXL6bt.js:51473:14)
    at Object.buildApp (file:///Users/forte/Downloads/vike-server/node_modules/.pnpm/vike@0.4.227-commit-68a216b_react-streaming@0.4.2_react-dom@19.0.0_react@19.0.0__react@_e8a8303e0bcb5a465de39bca10270746/node_modules/vike/dist/esm/node/plugin/plugins/build/pluginBuildApp.js:23:29)
    at Module.build (file:///Users/forte/Downloads/vike-server/node_modules/.pnpm/vike@0.4.227-commit-68a216b_react-streaming@0.4.2_react-dom@19.0.0_react@19.0.0__react@_e8a8303e0bcb5a465de39bca10270746/node_modules/vike/dist/esm/node/api/build.js:22:9)
    at cmdBuild (file:///Users/forte/Downloads/vike-server/node_modules/.pnpm/vike@0.4.227-commit-68a216b_react-streaming@0.4.2_react-dom@19.0.0_react@19.0.0__react@_e8a8303e0bcb5a465de39bca10270746/node_modules/vike/dist/esm/node/cli/entry.js:51:9)
    at cli (file:///Users/forte/Downloads/vike-server/node_modules/.pnpm/vike@0.4.227-commit-68a216b_react-streaming@0.4.2_react-dom@19.0.0_react@19.0.0__react@_e8a8303e0bcb5a465de39bca10270746/node_modules/vike/dist/esm/node/cli/entry.js:14:9) {
  code: 'PLUGIN_ERROR',
  plugin: 'commonjs--resolver',
  hook: 'resolveId',
  [Symbol(augmented)]: true
}
```

And I still don't understand how to implement a callback for a cron job in Vike Server.

```
import { serve } from "vike-server/hono/serve"
import { Hono } from "hono"

const port = 3000

export function boot(instance: Hono) {
  return serve(instance,
    {
      port,
    },
    /* // remarked due to an error
    () => {
      console.log("Cron Job")
    },
    */
  )
}
```

**Comment by magne4000** [comment]
@fortezhuo To fix the build, you can manually add `vike` Vite plugin to the `vite.config.ts`:
```ts
import vike from 'vike/plugin';

export default defineConfig({
  // put vike first
  plugins: [vike(), ...],
  ...
})
```

This is an unforeseen side effect of the new Vite API, and we're trying to find the best solution to fix that automatically.

> And I still don't understand how to implement a callback for a cron job in Vike Server.

That's because it's not implemented, I'm trying to have the smallest API footprint.
What do you actually mean by cron job here? I can manage to add a callback to all `serve` function when the underlying server is ready, is that what you need?

**Comment by fortezhuo** [comment]
@magne4000 
Put ```vike()``` can fix the problem. Thanks!


https://github.com/vikejs/vike-server/blob/64932684d25b241c303ee810d9c692408bea8329/packages/vike-server/src/handlers/serve.ts#L62

Yes. Callback is called while the underlying server is ready, include custom console print
I think you can add a callback here, if the callback defined, run the callback instead 

```ts
export function onReady(options: { port: number; isHttps?: boolean },callback?:Function ) {
  return () => {
    if (import.meta.hot) {
      if (import.meta.hot.data.vikeServerStarted) {
        import.meta.hot.send('vike-server:reloaded')
        return
      }
      import.meta.hot.data.vikeServerStarted = true
    }
    if(callback){
       callback()
    } else {
       console.log(`Server running at ${options.isHttps ? 'https' : 'http'}://localhost:${options.port}`)
   }
  }
}
```

**Comment by magne4000** [comment]
@fortezhuo `1.0.6` adds a [callback parameter](https://github.com/vikejs/vike-server/pull/90) to `serve`.

**Comment by magne4000** [comment]
Wait a few minutes, [the signature will change in `1.0.7`](https://github.com/vikejs/vike-server/pull/90#issuecomment-2760560632).

**Comment by magne4000** [comment]
@fortezhuo `1.0.7` released with an `onReady` option. Please check #91 for an example.
